export const DamaContract = `[
  {"prim":"storage","args":[
   {"prim":"pair","args":[
    {"prim":"pair","args":[
     {"prim":"pair","args":[
      {"prim":"pair","args":[
       {"prim":"pair","args":[
        {"prim":"pair","args":[
         {"prim":"pair","args":[
          {"prim":"list","args":[
           {"prim":"pair","args":[
            {"prim":"pair","args":[
             {"prim":"pair","args":[
              {"prim":"bool","annots":["%alive"]},{"prim":"bool","annots":["%isKing"]}]
             },{"prim":"int","annots":["%x"]}]
            },{"prim":"int","annots":["%y"]}]
           }]
          ,"annots":["%blackPieces"]},{"prim":"bool","annots":["%ended"]}]
         },{"prim":"address","annots":["%player1"]}]
        },{"prim":"address","annots":["%player2"]}]
       },{"prim":"address","annots":["%recentPlayer"]}]
      },
      {"prim":"list","args":[
       {"prim":"pair","args":[
        {"prim":"pair","args":[
         {"prim":"pair","args":[
          {"prim":"bool","annots":["%alive"]},{"prim":"bool","annots":["%isKing"]}]
         },{"prim":"int","annots":["%x"]}]
        },{"prim":"int","annots":["%y"]}]
       }]
      ,"annots":["%redPieces"]}]
     },
     {"prim":"pair","args":[
      {"prim":"pair","args":[
       {"prim":"pair","args":[
        {"prim":"pair","args":[
         {"prim":"bool","annots":["%eaten"]},{"prim":"bool","annots":["%isBlock"]}]
        },{"prim":"bool","annots":["%moveTwoStep"]}]
       },{"prim":"int","annots":["%somethingToEat"]}]
      },{"prim":"bool","annots":["%validMove"]}]
     ,"annots":["%status"]}]
    },{"prim":"string","annots":["%winner"]}]
   }]
  },
  {"prim":"parameter","args":[
   {"prim":"pair","args":[
    {"prim":"pair","args":[
     {"prim":"pair","args":[
      {"prim":"int","annots":["%start_x"]},{"prim":"int","annots":["%start_y"]}]
     },{"prim":"int","annots":["%target_x"]}]
    },{"prim":"int","annots":["%target_y"]}]
   }]
  },
  {"prim":"code","args":[
   [{"prim":"DUP"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SENDER"},{"prim":"COMPARE"},{"prim":"NEQ"},
   {"prim":"IF","args":[
    [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: sp.sender != self.data.recentPlayer"}]},{"prim":"FAILWITH"}]]]
   },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
   {"prim":"IF","args":[
    [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: ~ self.data.ended"}]},{"prim":"FAILWITH"}]]]
   },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
   {"prim":"IF","args":[
    [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
    {"prim":"ITER","args":[
     [{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
     {"prim":"IF","args":[
      [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
     },
     {"prim":"IF","args":[
      [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
     },
     {"prim":"IF","args":[
      [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SENDER"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       },{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       }]],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       },{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       }]]]
      }]],[[]]]
     },{"prim":"DROP"}]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CDR"},
    {"prim":"IF","args":[
     [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: self.data.status.validMove"}]},{"prim":"FAILWITH"}]]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
    {"prim":"MAP","args":[
     [{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
     {"prim":"MAP","args":[
      [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
       {"prim":"ITER","args":[
        [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      },{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
       {"prim":"ITER","args":[
        [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      },{"prim":"DUP"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
       {"prim":"ITER","args":[
        [{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      }]]
     },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"}]]
    },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
    {"prim":"DIP","args":[
     [[{"prim":"CAR"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
    },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"GE"},
    {"prim":"IF","args":[
     [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
     {"prim":"IF","args":[
      [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: self.data.status.eaten"}]},{"prim":"FAILWITH"}]]]
     }]],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
     {"prim":"IF","args":[
      [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: ~ self.data.status.moveTwoStep"}]},{"prim":"FAILWITH"}]]]
     },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
     {"prim":"MAP","args":[
      [{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DUP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DUP"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"COMPARE"},{"prim":"EQ"},
       {"prim":"IF","args":[
        [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
       }]],[[]]]
      }]]
     },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"}]]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
    {"prim":"ITER","args":[
     [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"COMPARE"},{"prim":"EQ"},
     {"prim":"IF","args":[
      [[]],[[]]]
     },{"prim":"DROP"}]]
    },{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"LE"},
    {"prim":"IF","args":[
     [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
    }]],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
    {"prim":"ITER","args":[
     [{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
     {"prim":"IF","args":[
      [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
     },
     {"prim":"IF","args":[
      [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
     },
     {"prim":"IF","args":[
      [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SENDER"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       },{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       }]],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       },{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"GE"},
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"LE"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
       },
       {"prim":"IF","args":[
        [[{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"}]],[[]]]
       }]]]
      }]],[[]]]
     },{"prim":"DROP"}]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CDR"},
    {"prim":"IF","args":[
     [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: self.data.status.validMove"}]},{"prim":"FAILWITH"}]]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
    {"prim":"MAP","args":[
     [{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
     {"prim":"MAP","args":[
      [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
       {"prim":"ITER","args":[
        [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"7"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      },{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
       {"prim":"ITER","args":[
        [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"7"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      },{"prim":"DUP"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"-1"}]},{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
       {"prim":"ITER","args":[
        [{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"5"}]},{"prim":"DIG","args":[{"int":"4"}]},{"prim":"DROP"}]],[[]]]
        },{"prim":"DROP"}]]
       },{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
       {"prim":"IF","args":[
        [[{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"ADD"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"},
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"PUSH","args":[{"prim":"int"},{"int":"-2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SUB"},{"prim":"COMPARE"},{"prim":"EQ"}]]]
        },
        {"prim":"IF","args":[
         [{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]}],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"}]]]
        },
        {"prim":"IF","args":[
         [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
         {"prim":"IF","args":[
          [[{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
         },
         {"prim":"IF","args":[
          [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"7"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
          {"prim":"IF","args":[
           [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
           {"prim":"DIP","args":[
            [[{"prim":"CAR"},{"prim":"DUP"},
            {"prim":"DIP","args":[
             [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
            },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
           },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
          }]],[[]]]
         }]],[[]]]
        }]],[[]]]
       }]],[[]]]
      }]]
     },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"4"}]},{"prim":"DIG","args":[{"int":"3"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"}]]
    },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
    {"prim":"DIP","args":[
     [[{"prim":"CAR"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
    },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"GE"},
    {"prim":"IF","args":[
     [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
     {"prim":"IF","args":[
      [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: self.data.status.eaten"}]},{"prim":"FAILWITH"}]]]
     }]],[[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"NOT"},
     {"prim":"IF","args":[
      [[]],[[{"prim":"PUSH","args":[{"prim":"string"},{"string":"WrongCondition: ~ self.data.status.moveTwoStep"}]},{"prim":"FAILWITH"}]]]
     },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},
     {"prim":"MAP","args":[
      [{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"},
      {"prim":"IF","args":[
       [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"EQ"}]],[{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]}]]
      },
      {"prim":"IF","args":[
       [[{"prim":"DUP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DUP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"CAR"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"DUP"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"7"}]},{"prim":"COMPARE"},{"prim":"EQ"},
       {"prim":"IF","args":[
        [[{"prim":"DUP"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"SWAP"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
       }]],[[]]]
      }]]
     },{"prim":"SWAP"},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"DUP"},
        {"prim":"DIP","args":[
         [[{"prim":"CAR"},{"prim":"DUP"},
         {"prim":"DIP","args":[
          [[{"prim":"CAR"},{"prim":"DUP"},
          {"prim":"DIP","args":[
           [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
          },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
         },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
        },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DROP"}]]]
    },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},
    {"prim":"ITER","args":[
     [{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"True"}]},{"prim":"COMPARE"},{"prim":"EQ"},
     {"prim":"IF","args":[
      [[]],[[]]]
     },{"prim":"DROP"}]]
    },{"prim":"PUSH","args":[{"prim":"int"},{"int":"1"}]},{"prim":"DIG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"3"}]},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"COMPARE"},{"prim":"LE"},
    {"prim":"IF","args":[
     [[{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"DUP"},
      {"prim":"DIP","args":[
       [[{"prim":"CAR"},{"prim":"DUP"},
       {"prim":"DIP","args":[
        [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
       },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
      },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"}]],[[]]]
    }]]]
   },{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"DUP"},
    {"prim":"DIP","args":[
     [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
    },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"int"},{"int":"0"}]},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"DUP"},
    {"prim":"DIP","args":[
     [[{"prim":"CAR"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
    },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"CAR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"SWAP"},{"prim":"DROP"},{"prim":"SWAP"},{"prim":"DUP"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DUP"},{"prim":"CAR"},{"prim":"CDR"},{"prim":"PUSH","args":[{"prim":"bool"},{"prim":"False"}]},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"DUP"},
    {"prim":"DIP","args":[
     [[{"prim":"CAR"},{"prim":"DUP"},
     {"prim":"DIP","args":[
      [[{"prim":"CAR"},{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
     },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
    },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"SWAP"},{"prim":"DUP"},
   {"prim":"DIP","args":[
    [[{"prim":"CAR"},{"prim":"CAR"},{"prim":"PAIR"}]]]
   },{"prim":"CDR"},{"prim":"SWAP"},{"prim":"PAIR"},{"prim":"DUG","args":[{"int":"2"}]},{"prim":"DROP"},{"prim":"DROP"},
   {"prim":"NIL","args":[
    {"prim":"operation"}]
   },{"prim":"PAIR"}]]
  }]`;
