export const DamaStorage = `{"prim":"Pair","args":[
    {"prim":"Pair","args":[
     {"prim":"Pair","args":[
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"Pair","args":[
          [
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"7"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"6"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"5"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"4"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"3"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"2"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"1"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"0"}]
           },{"int":"2"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"7"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"6"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"5"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"4"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"3"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"2"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"1"}]
           },{"int":"1"}]
          },
          {"prim":"Pair","args":[
           {"prim":"Pair","args":[
            {"prim":"Pair","args":[
             {"prim":"True"},{"prim":"False"}]
            },{"int":"0"}]
           },{"int":"1"}]
          }],{"prim":"False"}]
         },{"string":"tz1QXAD77BSjuD9W4AFq8rPTN1dk1gsDjYVG"}]
        },{"string":"tz1SaSyYcuPB1EoMHkC4fx9y6HwipWMAq8e7"}]
       },{"string":"tz1SaSyYcuPB1EoMHkC4fx9y6HwipWMAq8e7"}]
      },[
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"7"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"6"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"5"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"4"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"3"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"2"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"1"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"0"}]
       },{"int":"5"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"7"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"6"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"5"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"4"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"3"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"2"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"1"}]
       },{"int":"6"}]
      },
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"True"},{"prim":"False"}]
        },{"int":"0"}]
       },{"int":"6"}]
      }]]
     },
     {"prim":"Pair","args":[
      {"prim":"Pair","args":[
       {"prim":"Pair","args":[
        {"prim":"Pair","args":[
         {"prim":"False"},{"prim":"False"}]
        },{"prim":"False"}]
       },{"int":"0"}]
      },{"prim":"False"}]
     }]
    },{"string":""}]
   }`;
